### ISSUE TITLE
Improved Rockgrub Missing Image

### ISSUE THREAD

**Issue by RevanFan1** [Metious/MetiousSubnauticaMods#3]
When using the Improved Rockgrub mod, the rockgrubs don't have any icon in my inventory. Just a white box.

![Subnautica_64smG35RV9](https://user-images.githubusercontent.com/61678274/131394754-c9fad213-6bed-47e4-9e65-6bdc1b5b09ef.jpg)

**Comment by RevanFan1** [comment]
Also I have on other issue. All of the rockgrubs I've bred in containment stay on the ground and I can't pick them up.

**Comment by RevanFan1** [comment]
I think I figured it out. The download doesn't contain the Assets folder it should have.

**Comment by Metious** [comment]
This issue has been fixed, sorry for the inconvenience and thanks for reporting!
